### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by VNAPNIC** [finkinfridom/payload-auth0-plugin#45]
when I run project throw exception

```
import { CollectionConfig } from 'payload/types';
import { Auth0Strategy } from "payload-auth0-plugin";
import { PictureField } from "payload-auth0-plugin/dist/components";

const Users: CollectionConfig = {
  slug: "authCollection",
  auth: {
    strategies: [
      {
        name: Auth0Strategy.name,
        strategy: (ctx) => {
          return new Auth0Strategy(ctx, "authCollection");
        },
      },
    ],
  },
  fields: [
    {
      name: "picture",
      type: "text",
      admin: {
        hidden: true,
        condition: (data) => {
          return data.picture;
        },
      },
    },
    {
      name: "pictureVisual",
      type: "ui",
      admin: {
        position: "sidebar",
        condition: (_, siblingData) => {
          return siblingData.picture;
        },
        components: {
          Field: PictureField,
          Cell: PictureField,
        },
      },
    },
    {
      name: "sub",
      type: "text",
      admin: {
        readOnly: true,
        condition: (data) => {
          return data.sub;
        },
      },
    },
  ],
};
```

```
/Volumes/Work/project/cms/node_modules/payload-auth0-plugin/dist/index.js:1
import { Auth0Strategy } from "./strategies/Auth0Strategy";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1055:15)
    at Module._compile (node:internal/modules/cjs/loader:1090:27)
    at Module._compile (/Volumes/Work/project/cms/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at require.extensions.<computed> (/Volumes/Work/project/cms/node_modules/ts-node/src/index.ts:1045:43)
    at Object.newLoader [as .js] (/Volumes/Work/project/cms/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Volumes/Work/project/cms/src/collections/Users.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._compile (/Volumes/Work/project/cms/node_modules/pirates/lib/index.js:136:24)
    at Module.m._compile (/Volumes/Work/project/cms/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at require.extensions.<computed> (/Volumes/Work/project/cms/node_modules/ts-node/src/index.ts:1059:12)
    at Object.newLoader [as .ts] (/Volumes/Work/project/cms/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Volumes/Work/project/cms/src/payload.config.ts:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._compile (/Volumes/Work/project/cms/node_modules/pirates/lib/index.js:136:24)
    at Module.m._compile (/Volumes/Work/project/cms/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at require.extensions.<computed> (/Volumes/Work/project/cms/node_modules/ts-node/src/index.ts:1059:12)
    at Object.newLoader [as .ts] (/Volumes/Work/project/cms/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfig (/Volumes/Work/project/cms/node_modules/payload/src/config/load.ts:37:16)
    at init (/Volumes/Work/project/cms/node_modules/payload/src/init.ts:54:30)
    at initSync (/Volumes/Work/project/cms/node_modules/payload/src/init.ts:154:7)
    at Payload.init (/Volumes/Work/project/cms/node_modules/payload/src/index.ts:125:13)
    at Object.<anonymous> (/Volumes/Work/project/cms/src/server.ts:35:9)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module.m._compile (/Volumes/Work/project/cms/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> (/Volumes/Work/project/cms/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at main (/Volumes/Work/project/cms/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (/Volumes/Work/project/cms/node_modules/ts-node/src/bin.ts:288:3)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
```

**Comment by finkinfridom** [comment]
hey @VNAPNIC which version are you using? is it the latest?

**Comment by VNAPNIC** [comment]
@finkinfridom 
yup, i use version: "payload-auth0-plugin": "^0.0.9",


```
"dependencies": {
    "axios": "^1.2.0",
    "crypto": "^1.0.1",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "payload": "^1.2.4",
    "payload-auth0-plugin": "^0.0.9",
    "pino": "^8.7.0"
  },
  "devDependencies": {
    "@types/express": "^4.17.9",
    "copyfiles": "^2.4.1",
    "cross-env": "^7.0.3",
    "nodemon": "^2.0.6",
    "ts-node": "^9.1.1",
    "typescript": "^4.9.3"
  }
  ```

**Comment by finkinfridom** [comment]
HEY @VNAPNIC, I just find out I forgot to publish the latest package version.
Please update to 0.0.10 and it should be fixed.
let me know
thanks

**Comment by VNAPNIC** [comment]
thanks, @finkinfridom it is working for me.
